language: node_js

node_js:
    - 9.3.0
    
npm:
    - 5.6.0
    
cache:
  directories:
    - node_modules
    
install:
    npm install --save-dev jest
 
script:
    - npm test

notifications:
  email: false